### ISSUE TITLE
Error setting path in linux

### ISSUE THREAD

**Issue by mathmd** [jonjampen/obsidian-xournalpp#2]
**Describe the bug**
An error popped up saying `Error: Xournalpp path not set up correctly` when creating a new .xopp file from Obsidian (flatpak) in Fedora 40. Though, a file is created correctly in the vault directory. 

**To Reproduce**
1. Use the command `Xournal++: Create a new note` in Obsidian
2. See the error showing up.

**Expected behavior**
A link should be created from the Obsidian note to the xournal file or automatically open Xournal++ to edit the file.

**Operating System and Versions**
 - OS: fedora 40
 - Obsidian version: 1.6.7
 - Xournal++ Plugin version: 1.0.4

**Comment by jonjampen** [comment]
Hi,
thank you for reporting the issue!
I tested this on Debian Linux with Obsidian (.deb) and I did not get an error.

Regarding the expected behavior: When using the command `Xournal++: Create a new note`, it will create a new .xopp file (a copy of your template or the default template) and if you have `Auto export Xournal++ files` enabled, it will also export the .xopp file to a PDF. However, it will **not** create a link in a markdown file to the new file. It also does not open the Xournal++ file automatically.

If I understand you correctly, the problem is that it shows an error message, even though the feature works, is that correct? Or is there also something wrong with the file creation?
Does the automatic PDF export also work (if it is enabled in the settings)?

The error usually occurs if the terminal command `xournalpp --version` returns an error, could you try running that in a terminal (replace `xournalpp` with your custom installation path, if you set that in the plugin's settings)? Does that work or do you get an error?

If that works, could you use the shortcut `ctrl + shift + i` to open the console, then run the command  `Xournal++: Create a new note` again and let me know what error messages are logged to the console?

Thanks for taking the time!

**Comment by aerits** [comment]
I used `flatpak-spawn --host flatpak run com.github.xournalpp.xournalpp` as the installation path and to get it to work. And I enabled D-Bus session bus and D-Bus host bus with flatseal on obsidian.

**Comment by lguenth** [comment]
+1 for aerits recommendation if you have both Obsidian and Xournal++ installed as Flatpaks.
