### ISSUE TITLE
Edit in Xournal++ button not working

### ISSUE THREAD

**Issue by Anodyine** [jonjampen/obsidian-xournalpp#3]
**Describe the bug**
When I click on the Edit in Xournal++ button it opens up the window shown in the screenshot instead of opening xournal++

**To Reproduce**
1. Create a xournal++ note
2. open the associated pdf in obsidian
3. click on the "Edit in Xournal++" button
4. see window shown in screenshot

**Expected behavior**
To open xournal++ and allow me to edit

**Screenshots**
![Screenshot from 2024-08-27 14-12-45](https://github.com/user-attachments/assets/22796d07-2e2d-40d9-9cde-345a9bb8eac3)

**Operating System and Versions**
 - OS: Ubuntu 24.04
 - Obsidian version: 1.6.7
 - Xournal++ Plugin version: 1.0.4

**Additional context**

**Comment by jonjampen** [comment]
Thanks for reaching out!

To me, it looks like the error is that your system does not know what software to use to open `.xopp` files. You can test this by double-clicking on a `.xopp` file in the file explorer (the system file explorer and not the file explorer in Obsidian), My guess is it will open the same window as shown in your screenshot.

If that is the case, the solution would be to right-click on any `.xopp` file in the system file explorer, select `Open With` and choose `Xournal++` and make sure to activate `Always use for this file type`.

I hope this helps!

**Comment by Anodyine** [comment]
Thanks for the reply!

That's the first think I thought of too. I set up xournal++ as the default app for xopp files using open with. Then, I test it by double clicking on a xopp file as you suggested. It opens up with xournal++ as expected. However, the problem with the Edit with Xournal++ button in Obsidian persists. 

BTW, thanks for the plugin. I've been looking for a way to add links to handwritten notes in Obsidian and this plugin is so close to providing a solution!

**Comment by Anodyine** [comment]
I'm not super familiar with Obsidian plugins, so I'm not sure how to get you more info about what could be causing it. Maybe, if the user has set a path to Xournalpp, line 129 could be changed to run a terminal command that opens the file instead of using obsidian's openFile method. 

I changed it around a bit and this worked:

![image](https://github.com/user-attachments/assets/64ade557-4926-44e2-87e8-401b045ccc6f)

I had to change the params to pass the plugin in instead of plugin.app. Want me to make a pr that actually checks to see if the userPath exists and only uses the command if the user has it defined?

**Comment by jonjampen** [comment]
Thanks for your suggestion, I will think about it and let you know how to proceed.

Before that, could you also try the following: I just realized, that setting `Always open in` from the file explorer might not set that on a system-wide scope (sorry, I'm not that experience with Linux). Maybe it would help to set the MIME type association manually. Could you try running:
```
xdg-mime query default application/x-xopp
```

and see if it returns `com.github.xournalpp.xournalpp.desktop`?

If not, that might be the problem, and you could set it with:
```
xdg-mime default com.github.xournalpp.xournalpp.desktop application/x-xopp
```
For me (on Debian) this directly affects how Obsidian opens the file.

**Comment by Anodyine** [comment]
Thanks. I attempted to run those commands. At first, the x-xopp was associated with rnote, but I set it as you suggested. However the problem still persists:

![Screenshot from 2024-08-28 16-19-23](https://github.com/user-attachments/assets/6e2e9a0a-9562-4912-8d9c-b56df39c316f)

Also, it looks like my xournalpp is saving them as application/gzip. Is that incorrect?

**Comment by AnthonyMichaelTDM** [comment]
> Also, it looks like my xournalpp is saving them as application/gzip. Is that incorrect?

yeah I'm having the same problem, xournal shouldn't be doing that and I don't know why it is but that's what's causing this issue

**Comment by jonjampen** [comment]
> Also, it looks like my xournalpp is saving them as application/gzip. Is that incorrect?

That is really weird and should not be like that, for me the file type returns `application/x-xopp`. I guess that would be something to address with [Xournal++](https://github.com/xournalpp/xournalpp/issues). I wonder if it has something to do with the installation method deb vs Flatpack vs AppImage vs Snap (I am using the deb package).

I thought about your suggestions, and I think it is the best solution. Would you be able to create a PR for the following?
- Change the `openXournalppFile` function to use `exec` instead of `openFile`.
- Use `checkXoppSetup(plugin)` to get the system default path or the custom path if set by user.
- Pass plugin instead of plugin.app in every function call.

I think it is best if we just do it for all users, even if no custom path is set, as most use the system default path.

**Comment by jonjampen** [comment]
> Want me to make a pr?

I thought about your suggestions, and I think it is the best solution. Would you be able to create a PR for the following?
- Change the `openXournalppFile` function to use `exec` instead of `openFile`.
- Use `checkXoppSetup(plugin)` to get the system default path or the custom path if set by user.
- Pass plugin instead of plugin.app in every function call.

I think it is best if we just do it for all users, even if no custom path is set, as most use the system default path.
