### ISSUE TITLE
Xournal++ File is not Created 

### ISSUE THREAD

**Issue by SchwarzeLanze** [jonjampen/obsidian-xournalpp#5]
Thank you so far for developing this useful integration.
After clicking on the ribbon icon in Obsidian and entering a name no file gets created nor can be found in the vault 

**To Reproduce**
1. Follow the Dev installation instructions 
2. Follow the troubleshooting instruction from DEV
3. Click on ribbon icon in obsidian and enter a name 

**Expected behavior**
A created Xournal++ File 

**Operating System and Versions**
 - WIN 11
 - Obsidian version: v1.6.7
 - Xournal++ Plugin version: 1.0.6

**Additional context**
Obsidian Sync is in use

**Comment by jonjampen** [comment]
Hi,
thanks for reporting this issue and for the great feedback!
For me, the ribbon icon works as expected. Here a few questions that help me troubleshoot:

- Do you get an error message in the console (pressing `ctrl + shift + i` inside of Obsidian and the clicking on `Console`)?
- Do the other methods of creating a Xorunal++ file work (like the command `Xournal++: Create a new note` or by right-clicking on a folder in the Obsidian file explorer and clicking `Create new Xournal++`)?
- Could you check if the file is created in the system file explorer? Because .xopp files are not displayed in the Obsidian file explorer by default, only their respective PDF. So if you have disabled the setting `Auto export Xournal++ files` or there is an issue with the export, you won't see the .xopp file inside of Obsidian.

Thanks for the additional info!

**Comment by SchwarzeLanze** [comment]
Hi, thank you for replying so fast to your questions.

- Do you get an error message in the console (pressing ctrl + shift + i inside of Obsidian and then clicking on Console)?

No errors. In Obsidian, it appears that the file was created.

- Do the other methods of creating a Xournal++ file work (like the command Xournal++: Create a new note or by right-clicking on a folder in the Obsidian file explorer and clicking Create new Xournal++)?
Yes.


- Could you check if the file is created in the system file explorer? Because .xopp files are not displayed in the Obsidian file explorer by default, only their respective PDF. So if you have disabled the setting Auto export Xournal++ files or there is an issue with the export, you won't see the .xopp file inside of Obsidian.
That explains my issue because I expected to see a file even if it is not editable inside Obsidian.
